(defun Make()
	(load "Make.lisp")
	(load "Sorting.lisp")
	(load "MergeSort.lisp")
	(load "BubbleSort.lisp")
	(load "HeapSort.lisp")
	(load "QuickSort.lisp")
	(load "InsertionSort.lisp")
	(load "SelectionSort.lisp")
	(load "Tests.lisp")
)

(defun MakeTests()
	(Make)
	(testall)
)