(defun subCompare (x y typePredicate areEqual isLessThan)
	"Sum any two numbers after printing a message."
	;(format t "Comparing ~d and ~d. ~%" x y)
	(if (apply typePredicate (list x))
		(if (apply typePredicate (list y))
			(cond 
				((apply areEqual (list x y)) 0)
				((apply isLessThan (list x y)) -1)
				(T 1)
			)
			-1
		)
		(if (apply typePredicate (list y)) 1 NIL)
	)
)

(defun listCompare (listA listB)
	(case (compare (car listA) (car listB))
		( 0 (compare (cdr listA) (cdr listB)) )	
		( 1 1)
		( -1 -1)
		(otherwise NIL)
	)
)

(defun compare (x y)
	"Universal comaparer. Returns -1 if x is smaller than y, 0 if they are equal and 1 if y is smaller."
	(cond
		((and (null x) (null y)) 0)
		((null x) -1)
		((null y) 1)
		((subCompare x y #'numberp #'eql #'<))
		((subCompare x y #'characterp #'CHAR= #'CHAR<))
		((subCompare x y #'stringp #'STRING= #'STRING<))
		((listCompare x y))
		(T (format t "Can't compare ~d and ~d.~%" x y))
	)
)

(defun mergesort (sequence &aux len)
	(set len (length sequence))
	(if (= len 1) 
		sequence
		(own-merge 
			(mergesort (subseq sequence 0 (truncate len 2)) )
			(mergesort (subseq sequence (truncate len 2)) ) 
		)
	)	
)

(defun own-merge (listA listB &aux result)
	
	(when (and listA listB)
		(let ((compareResult (compare (car listA) (car listB))))
			(if (eq 0 compareResult) 
				(or
					(setq result (append result (list (car listB))))
					(setq listB (cdr listB) )
					(setq result (append result (list (car listA))))
					(setq listB (cdr listA) ) 
				)
			)
			(if (eq 1 compareResult)
				(or
					(setq result (append result (list (car listB))))
					(setq listB (cdr listB))
				)
			)
			(if (eq -1 compareResult)
				(or
					(setq result (append result (list (car listA))))
					(setq listB (cdr listA))
				)
			)
		)
	) 
	(unless (null listA) 
		(setq result (append result (list (car listA))))
		(setq listB (cdr listA))
	)
	(unless (null listB) 
		(setq result (append result (list (car listB))))
		(setq listB (cdr listB))		
	)
	result	
)

(defun append-and-cut (sequence sequenceName appended appendedName)
	(setq sequenceName(append sequence(list (car appended))))
	(setq appendedName(cdr appended) )
)